name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build sender
      run: |
        cd sender
        javac Sender.java
        java -ea Sender
    - name: build receiver
      run: g++ -o testreceiver receiver/src/*cpp* receiver/test/*hpp* -I receiver/include/